on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release Next.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Npm dependencies
        run: npm install
<<<<<<< HEAD

      - name: Build static website
        run: npm run build
=======
        

      - name: Build static website
        run: npm run build
        
>>>>>>> 575ad3140d8341f45ddbc13a8cb5c0d43db537ba

      - name: Build Docker image
        run: docker build -t amansingh13611/next_testing_image:latest .
        working-directory: .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.USER_NAME }} -p ${{ secrets.USER_PASS }}
          docker push amansingh13611/next_testing_image:latest 
        working-directory: .
<<<<<<< HEAD

      - name: Create and upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-artifacts
          path: ./out
=======
>>>>>>> 575ad3140d8341f45ddbc13a8cb5c0d43db537ba
